# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: db
    restart: always
    # uncomment for debugging
    ports:
      - 5432:5432/tcp 
    env_file:
      - global.env
    volumes:
      - ./dbInit:/docker-entrypoint-initdb.d/
      - ./dbdata:/var/lib/postgresql/data
      - ./pg_hba.conf:/conf/pg_hba.conf
    command: postgres -c hba_file=/conf/pg_hba.conf
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build: .
    container_name: flaskServer
    restart: always
    env_file:
      - global.env
      - web.env
    ports:
      - 80:80/tcp
    volumes:
      # mount app as read-only
      - ./code:/code:ro
      - ./.well-known:/.well-known:ro
    depends_on:
      - db
        # condition: service_healthy

volumes:
  dbInit:
  dbdata:
  code:
  pg_hba.conf:
  .well-known: