version: '3.1'

services:

  db:
    image: postgres
    container_name: db
    restart: always
    # uncomment for debugging
    ports:
      - 5432:5432/tcp 
    env_file:
      - global.env
    volumes:
      - ./dbInit:/docker-entrypoint-initdb.d/
      - ./dbdata:/var/lib/postgresql/data
      - ./pg_hba.conf:/conf/pg_hba.conf
    command: postgres -c hba_file=/conf/pg_hba.conf
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build: .
    container_name: flaskServer
    restart: always
    env_file:
      - global.env
      - web.env
    ports:
      - ${HTTP_PORT:-80}:${HTTP_PORT:-80}/tcp
      - ${HTTPS_PORT:-443}:${HTTPS_PORT:-443}/tcp
    volumes:
      # mount app as read-only
      - ./code:/code:rw
      - ./.well-known:/.well-known:ro
      - /etc/letsencrypt:/letsencrypt:ro
      - ./.git:/.git:ro
    depends_on:
      - db
        # condition: service_healthy

  smtp:
    image: namshi/smtp
    container_name: smtp
    restart: always
    ports:
     - "25:25"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 81:80/tcp 
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=password

volumes:
  dbInit:
  dbdata:
  code:
  pg_hba.conf:
  .well-known:
  .git: