# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - global.env
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: flaskServer
    restart: always
    env_file:
      - global.env
      - web.env
    ports:
      # standard
      - 80:80/tcp
      # dev
      - 5000:5000/tcp
    volumes:
      # mount app as read-only
      - .:/app/:ro

volumes:
  dbdata:
  .: